### ISSUE TITLE
EOFError connecting to FreeBSD remotes

### ISSUE THREAD

**Issue by rayrapetyan** [tomerfiliba/plumbum#177]
This issue is similar to #111 (I left comment there but issue was closed).
Whenever you attempt to do something with remote FreeBSD machine, operation ends with:
```
Running ['/usr/bin/ssh', '-i', '/home/robert/.ssh/id_rsa', '-T', 'robert@somehosthere']
Running "true ; echo $? ; echo '--.END283687202.333.--' ; echo '--.END283687202.333.--' 1>&2"
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    sys.exit(run())
  File "test.py", line 9, in run
    r = SshMachine("ara-traf-xml1-freebsd", user="robert", keyfile="/home/robert/.ssh/id_rsa")
  File "/ara/devel/flask-virtenv/lib/python2.7/site-packages/plumbum/machines/ssh_machine.py", line 106, in __init__
    new_session = new_session)
  File "/ara/devel/flask-virtenv/lib/python2.7/site-packages/plumbum/machines/remote.py", line 129, in __init__
    self._session = self.session(new_session = new_session)
  File "/ara/devel/flask-virtenv/lib/python2.7/site-packages/plumbum/machines/ssh_machine.py", line 150, in session
    self.encoding, isatty, self.connect_timeout)
  File "/ara/devel/flask-virtenv/lib/python2.7/site-packages/plumbum/machines/session.py", line 141, in __init__
    self.run("")
  File "/ara/devel/flask-virtenv/lib/python2.7/site-packages/plumbum/machines/session.py", line 224, in run
    return run_proc(self.popen(cmd), retcode)
  File "/ara/devel/flask-virtenv/lib/python2.7/site-packages/plumbum/commands/processes.py", line 186, in run_proc
    stdout, stderr = proc.communicate()
  File "/ara/devel/flask-virtenv/lib/python2.7/site-packages/plumbum/machines/session.py", line 92, in communicate
    line = pipe.readline()
  File "/ara/devel/flask-virtenv/lib/python2.7/site-packages/plumbum/machines/session.py", line 42, in readline
    raise EOFError()
EOFError
```
Tried recommendations from #111 - they didn't work.

**Comment by henryiii** [comment]
I'm thinking #111 is more valid, switching to that one.
