### ISSUE TITLE
Plumbum attempts to execute directories

### ISSUE THREAD

**Issue by asottile** [tomerfiliba/plumbum#234]
Heads were scratched until we figured out who was to blame here:

(Reproduced with 1.6)

```python
$ rm -rf git venv && mkdir git && virtualenv venv && ./venv/bin/pip install plumbum && PATH=. ./venv/bin/python -c "from plumbum.cmd import git; git('status')"; rm -rf git venv
New python executable in venv/bin/python
Installing setuptools, pip...done.
Downloading/unpacking plumbum
  Downloading plumbum-1.6.0.tar.gz (77kB): 77kB downloaded
  Running setup.py (path:/tmp/venv/build/plumbum/setup.py) egg_info for package plumbum
Installing collected packages: plumbum
  Running setup.py install for plumbum
Successfully installed plumbum
Cleaning up...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/venv/lib/python2.6/site-packages/plumbum/commands/base.py", line 89, in __call__
    return self.run(args, **kwargs)[1]
  File "/tmp/venv/lib/python2.6/site-packages/plumbum/commands/base.py", line 218, in run
    with self.bgrun(args, **kwargs) as p:
  File "/usr/lib64/python2.6/contextlib.py", line 16, in __enter__
    return self.gen.next()
  File "/tmp/venv/lib/python2.6/site-packages/plumbum/commands/base.py", line 174, in bgrun
    p = self.popen(args, **kwargs)
  File "/tmp/venv/lib/python2.6/site-packages/plumbum/machines/local.py", line 107, in popen
    **kwargs)
  File "/tmp/venv/lib/python2.6/site-packages/plumbum/machines/local.py", line 257, in _popen
    stderr = stderr, cwd = str(cwd), env = env, **kwargs)  # bufsize = 4096
  File "/usr/lib64/python2.6/subprocess.py", line 623, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1141, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

The thing it is trying to execute is `./git` which is a directory.

**Comment by henryiii** [comment]
Nice catch. It's an easy patch (changes two lines), but I want too look into it a little further to see if can do it without two separate stat calls.

FYI:
The `_which` functions in plumbum/plumbum/machines/local.py would look like:
```python
if fn.access("x") and not fn.is_dir():
```

**Comment by henryiii** [comment]
Looks like this is the best way to do it. I'll assume this is small enough and simple enough to commit the patch directly (@tomerfiliba, if you would prefer me to make it a pull request, I can). I'll try to do it later today.
