### ISSUE TITLE
`FG` and `BG` break `locals()` on Python (3)

### ISSUE THREAD

**Issue by AndydeCleyre** [tomerfiliba/plumbum#262]
`plumbum` v1.6.1.r13.gf3ad3fa

```python
>>> locals()
{'__name__': '__main__', '__spec__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__builtins__': <module 'builtins' (built-in)>, '__doc__': None, '__package__': None}
>>> from plumbum import BG
>>> locals()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/plumbum/commands/modifiers.py", line 68, in __repr__
    for cls in self.__mro__:
AttributeError: 'BG' object has no attribute '__mro__'
```

**Comment by AndydeCleyre** [comment]
Perfect, thanks!
