### ISSUE TITLE
Exception handling loses output, makes troubleshooting difficult

### ISSUE THREAD

**Issue by rsyring** [tomerfiliba/plumbum#263]
I have ran into the following behavior which has made troubleshooting difficult:

- Some programs write error output to stdout and not stderr.  It appears that plumbum only captures stderr in an exception stack trace.  It would be helpful to capture stdout too.
- I've found no way to tie into plumbum logging to get stdout of failed commands.
- When using piping, I've had the second command fail, which causes the first command to fail, but the stack trace is only for the first command when, in reality, it was the second command that had the error.  It's messages and return code are lost.

Most of these issues are caused for me when trying to pipe `zfs send` to `zfs receive` like so:

```python
zfs = sudo[plumbum.local['/sbin/zfs']]
zfs[['send'] + source_dataset] | zfs[['receive'] + dest_dataset]
```

If the `zfs receive` fails, I can get exceptions like the following:

```
Traceback (most recent call last):
  File "/opt/kilo/src/kilo/cli.py", line 108, in invoke
    retval = click.Command.invoke(self, ctx)
  File "/opt/kilo/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/kilo/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/opt/kilo/src/kilo/commands/zfs.py", line 80, in snapsync
    command.execute()
  File "/opt/kilo/src/kilo/libs/zfs.py", line 25, in execute
    send_receive()
  File "/opt/kilo/lib/python3.4/site-packages/plumbum/commands/base.py", line 90, in __call__
    return self.run(args, **kwargs)[1]
  File "/opt/kilo/lib/python3.4/site-packages/plumbum/commands/base.py", line 220, in run
    return p.run()
  File "/opt/kilo/lib/python3.4/site-packages/plumbum/commands/base.py", line 182, in runner
    return run_proc(p, retcode, timeout)
  File "/opt/kilo/lib/python3.4/site-packages/plumbum/commands/processes.py", line 206, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/opt/kilo/lib/python3.4/site-packages/plumbum/commands/processes.py", line 23, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/opt/kilo/lib/python3.4/site-packages/plumbum/commands/base.py", line 309, in verify
    proc.srcproc.verify(or_retcode, timeout, stdout, stderr)
  File "/opt/kilo/lib/python3.4/site-packages/plumbum/machines/base.py", line 19, in verify
    stdout, stderr)
plumbum.commands.processes.ProcessExecutionError: Command line: ['/usr/bin/sudo', '/sbin/zfs', 'send', 'rpool/ROOT@zfsnap-yearly-2016-01-06_22.00.00--3y']
Exit code: 1
Stderr:  | warning: cannot send 'rpool/ROOT@zfsnap-yearly-2016-01-06_22.00.00--3y': Broken pipe
```

The problem with this is that while `zfs send` did error out, the real problem occurred on the receive side.  For some reason, the receive failed causing a broken pipe.  But, all the data regarding the failure reason is lost to me.

**Comment by henryiii** [comment]
Logging improved slightly in either 1.6.1 or master. Have you tested that? I'm fine with reviewing patches, by the way. :)

**Comment by sashkab** [comment]
@henryiii I have 1.6.7 and it is still looses output of the source app, which, I suspect was in the stderr. Any plans on fixing it, or suggesting where to look?
