### ISSUE TITLE
AttributeError: _cwd using cwd context manager over ssh

### ISSUE THREAD

**Issue by Panke** [tomerfiliba/plumbum#271]
```
Traceback (most recent call last):
  File "./test.py", line 10, in <module>
    mal["ls"]("-l")
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/panke/reps/tmsdev/venv/lib/python2.7/site-packages/plumbum/path/remote.py", line 337, in __call__
    self.chdir(prev)
  File "/home/panke/reps/tmsdev/venv/lib/python2.7/site-packages/plumbum/path/remote.py", line 316, in chdir
    del self.remote._cwd
AttributeError: _cwd
```

Seems to hit on the second use of the cwd context manager over ssh. Version used:  1.6.1.

```python
#! /usr/bin/env python2
from plumbum import SshMachine

if __name__ == '__main__':
  ma = SshMachine("crane", user="panke")
  with ma.cwd("/tmp/"):
    ma["ls"]()

  with ma.cwd("/var/"):
    mal["ls"]("-l")
```

**Comment by henryiii** [comment]
That's an easy fix; `_cwd` only exists if the directory is current. I'll put in a patch and test.

If you need it to work in the mean time, call cwd on the remote in-between context managers.

**Comment by henryiii** [comment]
Should be fixed, let me know if it still has problems! `_ssh` is just a cache for the cwd if it is not known.
