### ISSUE TITLE
Running an ncurses program via plumbum

### ISSUE THREAD

**Issue by bfo** [tomerfiliba/plumbum#292]
Hi, I'm trying to run a Kconfig frontend, kconfig-nconf, using plumbum 1.6.2. However, after the call, my script hangs.

```
Python 3.5.2 (default, Jun 28 2016, 08:46:01) 
[GCC 6.1.1 20160602] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from plumbum import local
>>> P = local['kconfig-nconf']
>>> print(P)
/usr/bin/kconfig-nconf
>>> P('Kconfig')
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/@@/.local/lib/python3.5/site-packages/plumbum/commands/base.py", line 90, in __call__
    return self.run(args, **kwargs)[1]
  File "/home/@@/.local/lib/python3.5/site-packages/plumbum/commands/base.py", line 220, in run
    return p.run()
  File "/home/@@/.local/lib/python3.5/site-packages/plumbum/commands/base.py", line 182, in runner
    return run_proc(p, retcode, timeout)
  File "/home/@@/.local/lib/python3.5/site-packages/plumbum/commands/processes.py", line 196, in run_proc
    stdout, stderr = proc.communicate()
  File "/usr/lib/python3.5/subprocess.py", line 1072, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1715, in _communicate
    ready = selector.select(timeout)
  File "/usr/lib/python3.5/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt
>>> 
```

Is running an ncurses program like this supported in plumbum?

**Comment by henryiii** [comment]
It probably is expecting input. Try something like
```python
from plumber import FG
P['Kconfig'] & FG
```
To at least see what it's trying to do. You'll probably need to pipe input to it, too. If the program is trying to read the dimensions of the screen, etc., it might be a bit harder to get it to work.

**Comment by bfo** [comment]
Ah, there was my mistake:
I should have done:
`P['Kconfig'] & FG`
instead of
`P('Kconfig')`
The latter blocks, the former runs fine, showing the program's interface as usual.
Thanks a ton, @henryiii
