### ISSUE TITLE
AttributeError: 'SshMachine' object has no attribute 'env'

### ISSUE THREAD

**Issue by schtibe** [tomerfiliba/plumbum#293]
I'm trying to Ssh on a remote machine, and get following error:

```
Traceback (most recent call last):
  File "wakeonlan", line 49, in <module>
    main()
  File "wakeonlan", line 44, in main
    wake_remotely(args.host)
  File "wakeonlan", line 30, in wake_remotely
    globals()[func_name]()
  File "wakeonlan", line 22, in remote_wake_huckfinn
    with SshMachine("host", user="user") as rem:
  File "/usr/lib/python3.5/site-packages/plumbum/machines/ssh_machine.py", line 106, in __init__
    new_session = new_session)
  File "/usr/lib/python3.5/site-packages/plumbum/machines/remote.py", line 164, in __init__
    self.env = RemoteEnv(self)
  File "/usr/lib/python3.5/site-packages/plumbum/machines/remote.py", line 38, in __init__
    BaseEnv.__init__(self, self.remote.path, ":")
  File "/usr/lib/python3.5/site-packages/plumbum/machines/env.py", line 37, in __init__
    self._update_path()
  File "/usr/lib/python3.5/site-packages/plumbum/machines/env.py", line 40, in _update_path
    self._path.update(self.get("PATH", ""))
  File "/usr/lib/python3.5/site-packages/plumbum/machines/env.py", line 24, in update
    self[:] = [self._path_factory(p) for p in text.split(self._pathsep)]
  File "/usr/lib/python3.5/site-packages/plumbum/machines/env.py", line 24, in <listcomp>
    self[:] = [self._path_factory(p) for p in text.split(self._pathsep)]
  File "/usr/lib/python3.5/site-packages/plumbum/machines/remote.py", line 202, in path
    p = self.env.expanduser(p)
AttributeError: 'SshMachine' object has no attribute 'env'
```

The error occurs on creation of the SshMachine:

```
with SshMachine("host", user="user") as rem:
    pass
```

It can be easily reproduced when you put some path with ~ into the PATH environment variable on the remote host:

`export PATH=$PATH":~/bin:"`

I used pyhon 3.5.2 with plumbum 1.6.2

**Comment by rrei** [comment]
This happens with `ParamikoMachine` as well. 
I'm using plumbum 1.6.3 on python 3.6.2.

**Comment by henryiii** [comment]
Sure, that would be great!

**Comment by rrei** [comment]
Here it is ;) #347
