### ISSUE TITLE
SshMachine() hangs few seconds after an exception

### ISSUE THREAD

**Issue by Asher256** [tomerfiliba/plumbum#306]
This exception is raised by SshMachine() when I try to connect to a host that does not exist:
```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.5/site-packages/plumbum/machines/session.py", line 108, in communicate
    line = pipe.readline()
  File "/home/user/.local/lib/python3.5/site-packages/plumbum/machines/session.py", line 56, in readline
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.bin/gl/nssh", line 119, in <module>
    main()
  File "/home/user/.bin/gl/nssh", line 113, in main
    RemoteShell(host=sys.argv[1])
  File "/home/user/.bin/gl/nssh", line 44, in __init__
    self.connect(host)
  File "/home/user/.bin/gl/nssh", line 90, in connect
    self.ssh = SshMachine(self.host)
  File "/home/user/.local/lib/python3.5/site-packages/plumbum/machines/ssh_machine.py", line 106, in __init__
    new_session = new_session)
  File "/home/user/.local/lib/python3.5/site-packages/plumbum/machines/remote.py", line 162, in __init__
    self._session = self.session(new_session = new_session)
  File "/home/user/.local/lib/python3.5/site-packages/plumbum/machines/ssh_machine.py", line 172, in session
    self.encoding, isatty, self.connect_timeout)
  File "/home/user/.local/lib/python3.5/site-packages/plumbum/machines/session.py", line 169, in __init__
    self.run("")
  File "/home/user/.local/lib/python3.5/site-packages/plumbum/machines/session.py", line 252, in run
    return run_proc(self.popen(cmd), retcode)
  File "/home/user/.local/lib/python3.5/site-packages/plumbum/commands/processes.py", line 196, in run_proc
    stdout, stderr = proc.communicate()
  File "/home/user/.local/lib/python3.5/site-packages/plumbum/machines/session.py", line 121, in communicate
    raise SSHCommsChannel2Error(msgerr) if name=="2" else SSHCommsError(msg)
plumbum.machines.session.SSHCommsError: No communication channel detected. Does the remote exist?
```
After the exception above, plumbum hangs few seconds. It looks like it is waiting for the thread to complete (even when I catch the exception above + I quit with sys.exit(), plumbum is still hanging... It looks like a thread that wasn't canceled).

Thank you.

Asher256

**Comment by henryiii** [comment]
Fixed in master, see if that works for you.

**Comment by Asher256** [comment]
You fix solved the issue! 

I wanted to thank you for the Python module plumbum. It is an excellent replacement for openssh_wrapper + python_sh modules + it is pythonnic and fully compatible with Python 3. Keep up with the good work!
