### ISSUE TITLE
plumbum.commands.processes.ProcessExecutionError: for commands which return null

### ISSUE THREAD

**Issue by avatar-lavventura** [tomerfiliba/plumbum#403]
The shell command I want to run, which returns nothing:

    echo helloWorld | grep 'dummy'

-----

**plumbum version:**

Following line works:

    out=(echo["helloWorld"] | grep["h"])().strip()

---

But following line does not, what might be the reason?

    out=(echo["helloWorld"] | grep["dummy"])().strip()
    print(out)

Error I am having:

    Traceback (most recent call last):
      File "dd.py", line 6, in <module>
        out=(echo["helloWorld"] | grep["dummy"])().strip()
      File "/home/user/venv/lib/python3.5/site-packages/plumbum/commands/base.py", line 103, in __call__
        return self.run(args, **kwargs)[1]
      File "/home/user/venv/lib/python3.5/site-packages/plumbum/commands/base.py", line 240, in run
        return p.run()
      File "/home/user/venv/lib/python3.5/site-packages/plumbum/commands/base.py", line 201, in runner
        return run_proc(p, retcode, timeout)
      File "/home/user/venv/lib/python3.5/site-packages/plumbum/commands/processes.py", line 232, in run_proc
        return _check_process(proc, retcode, timeout, stdout, stderr)
      File "/home/user/venv/lib/python3.5/site-packages/plumbum/commands/processes.py", line 23, in _check_process
        proc.verify(retcode, timeout, stdout, stderr)
      File "/home/user/venv/lib/python3.5/site-packages/plumbum/commands/base.py", line 412, in verify
        dstproc_verify(retcode, timeout, stdout, stderr)
      File "/home/user/venv/lib/python3.5/site-packages/plumbum/machines/base.py", line 26, in verify
        stderr)
    plumbum.commands.processes.ProcessExecutionError: Command line: ['/bin/grep', 'dummy']
    Exit code: 1

**[Q]** How could I fix this error?

**Comment by smheidrich** [comment]
This happens because ``grep`` returns a non-zero exit code if it can't find the specified pattern in its input. As explained in [the section on exit codes in the docs](https://plumbum.readthedocs.io/en/latest/local_commands.html#exit-codes), there are two ways to handle this:

1. If you don't care about the exit code at all, specify ``retcode=None`` when you run the shell command, which will make it never raise an exception no matter what the exit code was:
``` python console
>>> out=(echo["helloWorld"] | grep["dummy"])(retcode=None).strip()
>>> out
''
```

2. If you know in advance which exit code(s) you want to accept, you can specify them using the ``retcode`` argument, either as a single value like ``retcode=0`` or as a tuple for multiple accepted values (``retcode=(0,1)``), as would be appropriate here:
``` python console
>>> out=(echo["helloWorld"] | grep["dummy"])(retcode=(0,1)).strip()
>>> out
''
```
I would go with this solution, because ``grep`` returns exit codes other than ``1`` if it genuinely fails for some reason, and you probably want your Python code to raise an exception in those cases. E.g. let's say you modify the grep command and accidentally add a (non-existent) filename to the arguments, it will still raise an exception with ``retcode=(0,1)`` because grep returns an exit code of ``2`` in this case:
``` python console
>>> out=(echo["helloWorld"] | grep["dummy", "nonexistent_filename"])(retcode=(0,1)).strip()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/smheidrich/cod_ext/plumbum/plumbum/commands/base.py", line 103, in __call__
    return self.run(args, **kwargs)[1]
  File "/home/smheidrich/cod_ext/plumbum/plumbum/commands/base.py", line 240, in run
    return p.run()
  File "/home/smheidrich/cod_ext/plumbum/plumbum/commands/base.py", line 201, in runner
    return run_proc(p, retcode, timeout)
  File "/home/smheidrich/cod_ext/plumbum/plumbum/commands/processes.py", line 232, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/home/smheidrich/cod_ext/plumbum/plumbum/commands/processes.py", line 23, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/home/smheidrich/cod_ext/plumbum/plumbum/commands/base.py", line 412, in verify
    dstproc_verify(retcode, timeout, stdout, stderr)
  File "/home/smheidrich/cod_ext/plumbum/plumbum/machines/base.py", line 22, in verify
    stderr)
plumbum.commands.processes.ProcessExecutionError: Command line: ['/bin/grep', 'dummy', 'nonexistent_filename']
Exit code: 2
Stderr:  | /bin/grep: nonexistent_filename: No such file or directory
```
Whereas this would fail silently with ``retcode=None``!

Hope this helps!
