### ISSUE TITLE
Filename is quoted, causing Cygwin script to fail

### ISSUE THREAD

**Issue by metaperl** [tomerfiliba/plumbum#435]
When you `print(last_game)` in the following script:
```python
#!/bin/env python3

from plumbum import local

ls = local["/usr/bin/ls"]
tail = local["/usr/bin/tail"]
leela = local["/cygdrive/c/Users/Owner/AppData/Local/Programs/Leela/Leela0110.exe"]

last_game = ls["-arth", '/cygdrive/c/Users/Owner/Downloads/*.sgf'] | tail["-1"]
print(last_game)

last_sgf = last_game()
print(last_sgf)

leela(last_sgf)
```

You get:
`/usr/bin/ls -arth '/cygdrive/c/Users/Owner/Downloads/*.sgf' | /usr/bin/tail -1` 

and the script fails with the error message
`/usr/bin/ls: cannot access '/cygdrive/c/Users/Owner/Downloads/*.sgf': No such file or directory` ... however if you remove the single-quotes from `/cygdrive/c/Users/Owner/Downloads/*.sgf` then the script executes just fine.

**Comment by henryiii** [comment]
You should use Plumbum paths here, something like: `ls["-arth", local.env.home('Downloads') // '*.sgf']`

**Comment by metaperl** [comment]
I'm not sure why your example had a double forward slash in it. Something about the `*.sgf` is not working:

```python
$ ls /cygdrive/c/Users/Owner/Downloads/*.sgf | head -3
/cygdrive/c/Users/Owner/Downloads/12780387-078-allonsy48-princepawn.sgf
/cygdrive/c/Users/Owner/Downloads/13682992-256-princepawn-preedano(1).sgf
/cygdrive/c/Users/Owner/Downloads/13682992-256-princepawn-preedano.sgf
]0;~/prg/fundinglink
Owner@DESKTOP-P80AOTU ~/prg/fundinglink
$ python -i
Python 3.6.4 (default, Jan  7 2018, 15:53:53) 
[GCC 6.4.0] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from plumbum import local
>>> ls = local["/usr/bin/ls"]
>>> ls["-arth",  local.path('/cygdrive/c/Users/Owner/Downloads')]()
"MobaXterm_Installer_v10.4\njdk-9.0.1_windows-x64_bin.exe\nclipgrab-3.6.6-cgorg.exe\nThe Joy of Clojure, 2nd Edition.pdf\nKindleForPC-installer-1.21.48017.exe\nideaIC-2017.3.1.exe\nligh
>>> ls["-arth",  local.path('/cygdrive/c/Users/Owner/Downloads/*.sgf')]()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/plumbum/commands/base.py", line 103, in __call__
    return self.run(args, **kwargs)[1]
  File "/usr/lib/python3.6/site-packages/plumbum/commands/base.py", line 240, in run
    return p.run()
  File "/usr/lib/python3.6/site-packages/plumbum/commands/base.py", line 201, in runner
    return run_proc(p, retcode, timeout)
  File "/usr/lib/python3.6/site-packages/plumbum/commands/processes.py", line 232, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/usr/lib/python3.6/site-packages/plumbum/commands/processes.py", line 23, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/usr/lib/python3.6/site-packages/plumbum/machines/base.py", line 26, in verify
    stderr)
plumbum.commands.processes.ProcessExecutionError: Command line: ['/usr/bin/ls', '-arth', '/cygdrive/c/Users/Owner/Downloads/*.sgf']
Exit code: 2
Stderr:  | /usr/bin/ls: cannot access '/cygdrive/c/Users/Owner/Downloads/*.sgf': No such file or directory
>>> 
```

``python
>>> ls["-arth",  local.path('/cygdrive/c/Users/Owner/Downloads/) // '*.sgf')]()
  File "<stdin>", line 1
    ls["-arth",  local.path('/cygdrive/c/Users/Owner/Downloads/) // '*.sgf')]()
                                                                      ^
SyntaxError: invalid syntax
>>> ls["-arth",  local.path('/cygdrive/c/Users/Owner/Downloads) // '*.sgf')]()
  File "<stdin>", line 1
    ls["-arth",  local.path('/cygdrive/c/Users/Owner/Downloads) // '*.sgf')]()
                                                                     ^
SyntaxError: invalid syntax
>>> ls["-arth",  local.path('/cygdrive/c/Users/Owner/Downloads) / '*.sgf')]()
  File "<stdin>", line 1
    ls["-arth",  local.path('/cygdrive/c/Users/Owner/Downloads) / '*.sgf')]()
                                                                    ^
SyntaxError: invalid syntax
```

**Comment by henryiii** [comment]
The double forward slash tells it to join *and* glob; that is, expand the star. I think there's a pathlib style `.glob()` method that does the same thing. Your other examples are missing a quote after Downloads.

**Comment by metaperl** [comment]
Yes `.glob()` is returning absolute paths instead of paths relative to the current directory. And the absolute path is using cygwin-style forward slashes but the program is expecting windows-style backward slashes:

```python
#!/bin/env python3

from plumbum import local

ls = local["/usr/bin/ls"]
tail = local["/usr/bin/tail"]
leela = local["/cygdrive/c/Users/Owner/AppData/Local/Programs/Leela/Leela0110.exe"]

with local.cwd('/cygdrive/c/Users/Owner/Downloads'):

    last_game = ls["-arth", local.path('.').glob('*.sgf')] | tail["-1"]
    print(last_game)

    last_sgf = last_game()
    print(f"last sgf is {last_sgf}")

    leela(last_sgf)
```

if it just returned the filename relative to the current working directory, then the issue of forward and backward slashes would disappear.
