### ISSUE TITLE
Unexpected behavior with silversearcher-ag

### ISSUE THREAD

**Issue by nkabir** [tomerfiliba/plumbum#447]
A search operation that works with [silversearcher-ag](https://github.com/ggreer/the_silver_searcher) on the command line does not work when wrapped in a Plumbum `local`:

In a folder that contains a file `demo.txt`, running `ag mystring123` produces:

```
demo.txt
3:mystring123

demo.py
6:result = pb_ag("mystring123")
```

However, when the same operation wrapped in Plumbum produces a stacktrace:

```
#!/usr/bin/python3

from plumbum import local

pb_ag = local["ag"]
result = pb_ag("mystring")
print(result)
```
Stacktrace

```
Traceback (most recent call last):
  File "./demo.py", line 6, in <module>
    result = pb_ag("mystring123")
  File "/home/nkabir/.local/opt/xcatalyst/venvs/bench-python-bench/lib/python3.6/site-packages/plumbum/commands/base.py", line 103, in __call__
    return self.run(args, **kwargs)[1]
  File "/home/nkabir/.local/opt/xcatalyst/venvs/bench-python-bench/lib/python3.6/site-packages/plumbum/commands/base.py", line 240, in run
    return p.run()
  File "/home/nkabir/.local/opt/xcatalyst/venvs/bench-python-bench/lib/python3.6/site-packages/plumbum/commands/base.py", line 201, in runner
    return run_proc(p, retcode, timeout)
  File "/home/nkabir/.local/opt/xcatalyst/venvs/bench-python-bench/lib/python3.6/site-packages/plumbum/commands/processes.py", line 232, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/home/nkabir/.local/opt/xcatalyst/venvs/bench-python-bench/lib/python3.6/site-packages/plumbum/commands/processes.py", line 23, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/home/nkabir/.local/opt/xcatalyst/venvs/bench-python-bench/lib/python3.6/site-packages/plumbum/machines/base.py", line 26, in verify
    stderr)
plumbum.commands.processes.ProcessExecutionError: Command line: ['/usr/bin/ag', 'mystring123']
Exit code: 1

```

Plumbum is fantastic for integrating Python into shell scripts. I use Silversearcher quite a bit and would very much like to combine these two excellent tools.

**Comment by nkabir** [comment]
My fault. I left off a trailing path in the command line arguments. Thanks, again, for an excellent tool!
