### ISSUE TITLE
It has normal output, but the python interpreter throws an exception.

### ISSUE THREAD

**Issue by clsteam** [tomerfiliba/plumbum#472]
Here is my code:
```
from plumbum import local
from plumbum.cmd import head
samtools = local['samtools']

chain = samtools['view', '-h', 'SRR3475323.bam'] | head["-n", 20] > 'bam.head'
chain()
```
I can get the correct output file "bam.head", but the python interpreter throws an exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zchen/miniconda3/lib/python3.7/site-packages/plumbum-1.6.7-py3.7.egg/plumbum/commands/base.py", line 96, in __call__
    return self.run(args, **kwargs)[1]
  File "/home/zchen/miniconda3/lib/python3.7/site-packages/plumbum-1.6.7-py3.7.egg/plumbum/commands/base.py", line 233, in run
    return p.run()
  File "/home/zchen/miniconda3/lib/python3.7/site-packages/plumbum-1.6.7-py3.7.egg/plumbum/commands/base.py", line 194, in runner
    return run_proc(p, retcode, timeout)
  File "/home/zchen/miniconda3/lib/python3.7/site-packages/plumbum-1.6.7-py3.7.egg/plumbum/commands/processes.py", line 247, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/home/zchen/miniconda3/lib/python3.7/site-packages/plumbum-1.6.7-py3.7.egg/plumbum/commands/processes.py", line 23, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/home/zchen/miniconda3/lib/python3.7/site-packages/plumbum-1.6.7-py3.7.egg/plumbum/commands/base.py", line 404, in verify
    proc.srcproc.verify(or_retcode, timeout, stdout, stderr)
  File "/home/zchen/miniconda3/lib/python3.7/site-packages/plumbum-1.6.7-py3.7.egg/plumbum/machines/base.py", line 22, in verify
    stderr)
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: -13
Command line: | /usr/local/bin/samtools view -h SRR3475323.bam
```

PS: 
The above code is intended to view the binary bam file, which is the result of a second-generation sequencing sequence alignment, [Samtools](http://www.htslib.org/) is used to process the bam file.

Yao

**Comment by clsteam** [comment]
In addition, when I remove `head["-n", 20]`, no exception will occur.

**Comment by AndydeCleyre** [comment]
Any difference with some parentheses?

```python
chain = ((samtools['view', '-h', 'SRR3475323.bam'] | head["-n", 20]) > 'bam.head')
```
