### ISSUE TITLE
No way to connect to remote machine with default shell Fish

### ISSUE THREAD

**Issue by Yajo** [tomerfiliba/plumbum#478]
I use http://fishshell.com/ in all my machines as default.

If that's the case, connecting with `SshMachine` or `ParamikoMachine` seems to be broken due to 769d03ca362bf89651420faf066b1595874ffefe:

```python
>>> from plumbum.machines import SshMachine                                                                                                                                                       

>>> machine = SshMachine("example.com", "root", 77970)                                                                                                                        
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/plumbum/machines/ssh_machine.py", line 124, in __init__
    new_session=new_session)
  File "/usr/lib/python3.7/site-packages/plumbum/machines/remote.py", line 172, in __init__
    self._session = self.session(new_session=new_session)
  File "/usr/lib/python3.7/site-packages/plumbum/machines/ssh_machine.py", line 204, in session
    self.connect_timeout)
  File "/usr/lib/python3.7/site-packages/plumbum/machines/session.py", line 189, in __init__
    self.run("")
  File "/usr/lib/python3.7/site-packages/plumbum/machines/session.py", line 277, in run
    return run_proc(self.popen(cmd), retcode)
  File "/usr/lib/python3.7/site-packages/plumbum/commands/processes.py", line 222, in run_proc
    stdout, stderr = proc.communicate()
  File "/usr/lib/python3.7/site-packages/plumbum/machines/session.py", line 120, in communicate
    line = pipe.readline()
  File "/usr/lib/python3.7/site-packages/plumbum/machines/session.py", line 62, in readline
    line = self.pipe.readline()
ValueError: readline of closed file
```

With `ParamikoMachine` it's quite similar, although it's and endless loop that you have to stop by hand:

```python
^CTraceback (most recent call last):
  File "./migrate.py", line 155, in <module>
    Migrate.run()
  File "/usr/lib/python3/dist-packages/plumbum/cli/application.py", line 498, in run
    f(inst, *a)
  File "./migrate.py", line 110, in download_v61
    machine = ParamikoMachine("example.com", "root", 77970)
  File "/usr/lib/python3/dist-packages/plumbum/machines/paramiko_machine.py", line 208, in __init__
    BaseRemoteMachine.__init__(self, encoding, connect_timeout)
  File "/usr/lib/python3/dist-packages/plumbum/machines/remote.py", line 159, in __init__
    self._session = self.session(new_session = new_session)
  File "/usr/lib/python3/dist-packages/plumbum/machines/paramiko_machine.py", line 241, in session
    return ShellSession(proc, self.custom_encoding, isatty)
  File "/usr/lib/python3/dist-packages/plumbum/machines/session.py", line 170, in __init__
    self.run("")
  File "/usr/lib/python3/dist-packages/plumbum/machines/session.py", line 254, in run
    return run_proc(self.popen(cmd), retcode)
  File "/usr/lib/python3/dist-packages/plumbum/commands/processes.py", line 196, in run_proc
    stdout, stderr = proc.communicate()
  File "/usr/lib/python3/dist-packages/plumbum/machines/session.py", line 108, in communicate
    line = pipe.readline()
  File "/usr/lib/python3/dist-packages/plumbum/machines/session.py", line 54, in readline
    line = self.pipe.readline()
  File "/usr/local/lib/python3.6/dist-packages/paramiko/file.py", line 291, in readline
    new_data = self._read(n)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/channel.py", line 1376, in _read
    return self.channel.recv_stderr(size)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/channel.py", line 747, in recv_stderr
    out = self.in_stderr_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/buffered_pipe.py", line 160, in read
    self._cv.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt
```

I don't know if this can be fixed or if, at least, you could add a `shell=` argument that lets us specify the shell to use with the connection... :roll_eyes:

**Comment by agoose77** [comment]
A lazy solution to this is to specify a different keyfile, and setup a different shell on `authorized-key`
