### ISSUE TITLE
Provide a way to handle KeyboardInterrupt elegantly in an Application

### ISSUE THREAD

**Issue by Yajo** [tomerfiliba/plumbum#490]
I have a `plumbum.cli.Application` where I have several subapps.

I'd like to make all the `main()` methods in them to handle elegantly a `KeyboardInterrupt` exception, so that if the user presses `Ctrl+C`, he doesn't get a ugly full traceback.

I tried with a decorator:

```py
def handle_user_exceptions(method):
    def _wrapper(*args, **kwargs):
        try:
            return method(*args, **kwargs)
        except KeyboardInterrupt:
            print(colors.red | "Execution stopped by user", file=sys.stderr)
            return 1
```

But when I decorate the `main()` methods, I cannot execute it:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/inspect.py", line 1126, in getfullargspec
    sigcls=Signature)
  File "/usr/lib64/python3.7/inspect.py", line 2208, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: None is not a callable object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yajo/Documentos/prodevel/copier/.venv/bin/copier", line 11, in <module>
    load_entry_point('copier', 'console_scripts', 'copier')()
  File "/home/yajo/Documentos/prodevel/copier/.venv/lib/python3.7/site-packages/plumbum/cli/application.py", line 553, in run
    ordered, tailargs = inst._validate_args(swfuncs, tailargs)
  File "/home/yajo/Documentos/prodevel/copier/.venv/lib/python3.7/site-packages/plumbum/cli/application.py", line 468, in _validate_args
    m = six.getfullargspec(self.main)
  File "/usr/lib64/python3.7/inspect.py", line 1132, in getfullargspec
    raise TypeError('unsupported callable') from ex
TypeError: unsupported callable
```

I guess this would be a good default behavior for applications, where  `Ctrl+C` is a common user interaction. It should be overridable, of course.

**Comment by AndydeCleyre** [comment]
You just forgot to return your `_wrapper` at the end of `handle_user_exceptions`.

**Comment by Yajo** [comment]
Yikes. :man_facepalming:  Thanks!
