### ISSUE TITLE
ModuleNotFoundError: No module named 'plumbum.version' / Docs on setuptools_scm requirements?

### ISSUE THREAD

**Issue by AndydeCleyre** [tomerfiliba/plumbum#534]
Hi,

I'm currently maintaining the AUR package, and stumbled updating to 1.7.0. 

I think something should be noted about the installation requirements of setuptools_scm, at least in the release notes, so that for example someone reading them on the github releases page is warned not to use the assets from that page for installation with pip. or similar.

---

Since 1c4f911927e95db3ad107f4bcc54b3e6482ecdf8, I was getting:

```py
Python 3.9.1 (default, Feb  6 2021, 06:49:13)
[GCC 10.2.0] on linux
>>> import plumbum
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/plumbum/__init__.py", line 56, in <module>
    from plumbum.version import version
ModuleNotFoundError: No module named 'plumbum.version'
```

The AUR PKGBUILD itself was just a wrapper around:

```console
$ python setup.py install --root="$pkgdir/" --optimize=1
```

But when I install in a venv, `version.py` was there. I saw it's generated with `setuptools_scm`.

So I tried changing it to:

```console
$ pip install --root "$pkgdir/" .
```

And I got this
<details><summary>complaint that not enough SCM data is available.</summary>

  ```
  Processing /home/andy/Code/aur/python-plumbum/src/plumbum-1.7.0
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /bin/python /usr/lib/python3.9/site-packages/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpjajm9lg5
       cwd: /tmp/pip-req-build-l1ovgg71
  Complete output (36 lines):
  Traceback (most recent call last):
    File "/usr/lib/python3.9/site-packages/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/lib/python3.9/site-packages/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/lib/python3.9/site-packages/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-_1awx74d/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 149, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-_1awx74d/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-_1awx74d/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 6, in <module>
      setup()
    File "/tmp/pip-build-env-_1awx74d/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.9/distutils/core.py", line 108, in setup
      _setup_distribution = dist = klass(attrs)
    File "/tmp/pip-build-env-_1awx74d/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 432, in __init__
      _Distribution.__init__(self, {
    File "/usr/lib/python3.9/distutils/dist.py", line 292, in __init__
      self.finalize_options()
    File "/tmp/pip-build-env-_1awx74d/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 708, in finalize_options
      ep(self)
    File "/tmp/pip-build-env-_1awx74d/overlay/lib/python3.9/site-packages/setuptools_scm/integration.py", line 61, in infer_version
      dist.metadata.version = _get_version(config)
    File "/tmp/pip-build-env-_1awx74d/overlay/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 173, in _get_version
      parsed_version = _do_parse(config)
    File "/tmp/pip-build-env-_1awx74d/overlay/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 134, in _do_parse
      raise LookupError(
  LookupError: setuptools-scm was unable to detect version for '/tmp/pip-req-build-l1ovgg71'.

  Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

  For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
  ----------------------------------------
ERROR: Command errored out with exit status 1: /bin/python /usr/lib/python3.9/site-packages/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpjajm9lg5 Check the logs for full command output.
  ```
</details>

Ah, well the PKGBUILD was relying on the build tools to first fetch `https://github.com/tomerfiliba/plumbum/archive/v${pkgver}.tar.gz`, so as the message says I need to either get PyPI tarballs or use a proper checkout.

As a git checkout seems overkill, I'm currently using the PyPI tarballs. This works, but makes package version bumps unnecessarily tedious, with URIs like `https://files.pythonhosted.org/packages/6c/fc/6cdaf59a001c707333869b054daf1e0df02978d261f20f8b082afcf189c3/plumbum-1.7.0-py2.py3-none-any.whl`.

**Comment by henryiii** [comment]
The easiest way to do it is to `SETUPTOOLS_SCM_PRETEND_VERSION=${pkgver}`, that will fix your issue when using `pip`. Agree, I'll add some notes!

**Comment by AndydeCleyre** [comment]
Excellent, thank you!

**Comment by henryiii** [comment]
I've added it to the [release notes](https://github.com/tomerfiliba/plumbum/releases/tag/v1.7.0) on the GitHub page , any other places you think it might be helpful?

**Comment by AndydeCleyre** [comment]
Probably just the downloads section on rtd. Thanks again!

**Comment by AndydeCleyre** [comment]
Should I care if installing with 

```console
$ python setup.py install
```

Creates paths like

```
.../site-packages/plumbum-0.0.0-py3.9.egg
.../site-packages/plumbum-0.0.0-py3.9.egg-info/
```

and the content of the files therein claim plumbum version `0.0.0`?

**Comment by henryiii** [comment]
You should be able to set the version with the env variable. That means setuptools_scm is installed but no git info was present.

**Comment by henryiii** [comment]
Ahh, no, that might be it ignoring the toml file. I should mention it needs toml too. Pip gets it for you.

**Comment by henryiii** [comment]
The exact build requirements are in pyproject.toml

**Comment by AndydeCleyre** [comment]
I ended up using the PyPI tarballs since I discovered an alternative more stable URI scheme they also use, and that's giving me the `0.0.0` metadata. Here's the current state of the PKGBUILD on my machine:

```bash
# Maintainer: Andy Kluger <https://t.me/andykluger>
# Maintainer: Florian Jacob <projects+arch AT florianjacob )DOT( de>
# Contributor: Milo Mirate <mmirate@gmx.com>

_name=plumbum
_ghrepo=tomerfiliba/$_name

pkgname=python-$_name
pkgdesc="A small yet feature-rich Python library for shell script-like programs, and more"
url="https://pypi.python.org/pypi/plumbum"

pkgver=1.7.0
pkgrel=2
sha256sums=('317744342c755319907c773cc87c3a30adaa3a41b0d34c0ce02d9d1904922dce')

source=("https://files.pythonhosted.org/packages/source/${_name::1}/$_name/$_name-$pkgver.tar.gz")

depends=(python)
makedepends=(python-setuptools)
optdepends=('python-paramiko: use pure Python for SSH2')

arch=('any')
license=('MIT')

build () {
  cd "$_name-$pkgver"
  python setup.py build
}

package () {
  cd "$_name-$pkgver"
  export PYTHONHASHSEED=0
  python setup.py install --root="$pkgdir" --optimize=1 --skip-build
}

```

**Comment by AndydeCleyre** [comment]
> The exact build requirements are in pyproject.toml

Ah, I'll add the extra reqs, I was only checking `setup.cfg` and `setup.py`

**Comment by henryiii** [comment]
Those would be makedepends. And the toml extra of setuptools_scm is really just the toml package.

**Comment by AndydeCleyre** [comment]
Yes, thank you, the version is properly set when I have setuptools-scm installed at build time

```sh
makedepends=(python-setuptools python-setuptools-scm python-toml)
```

**Comment by henryiii** [comment]
Great! I'll add mention of toml being required at build time tomorrowish.
